backend:
  name: git-gateway
  repo: schotsl/portfolio-nuxt
  branch: development
  commit_messages:
    create: ğŸ“ Created {{collection}} collection
    update: ğŸ“ Updated {{collection}} collection
    delete: ğŸ”¥ Deleted {{collection}} collection
    uploadMedia: ğŸ± Uploaded â€œ{{path}}â€
    deleteMedia: ğŸ”¥ Deleted â€œ{{path}}â€
    openAuthoring: "{{message}}"

media_folder: "public/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "images" # The src attribute for uploaded media will begin with /images/uploads

site_url: "https://portfolio-xwhvio.netlify.app"
logo_url: "https://portfolio-xwhvio.netlify.app/icon/favicon.svg"

collections:
  - name: "projects"
    label: "Projects"
    create: true
    editor: { preview: false }
    folder: "content/projects"
    extension: "json"
    fields:
      - name: "title"
        label: "Titel"
        widget: "string"
      - name: "Category"
        label: "Category"
        widget: "select"
        options:
          - { label: "Both", value: "both" }
          - { label: "Design", value: "design" }
          - { label: "Development", value: "development" }
      - name: "cover"
        label: "Cover"
        widget: "image"
        choose_url: false
        media_folder: "/public/images/projects"
        allow_multiple: false
      - name: "gif"
        label: "gif"
        widget: "image"
        choose_url: false
        media_folder: "/public/images/projects"
        allow_multiple: false
      - name: "video"
        label: "video"
        widget: "file"
        choose_url: false
        media_folder: "/public/videos/projects"
        allow_multiple: false