name: Push

on:
  push:
    branches:
      - development

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install NPM dependencies
        run: npm ci --ignore-scripts

      - name: Run NPM check
        run: npm run check

  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install NPM dependencies
        run: npm ci --ignore-scripts

      - name: Run NPM generate
        run: npm run generate

      - name: Archive artifact
        uses: actions/upload-artifact@main
        with:
          name: .output
          path: .output

  deploy:
    name: Deploy
    needs: [quality, generate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: .output
          path: .output

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: hosting:channel:deploy development
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}